CREATE TABLE IF NOT EXISTS admins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS associacoes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cnpj TEXT NOT NULL UNIQUE,
    responsavel TEXT NOT NULL,
    email TEXT NOT NULL,
    telefone TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    token TEXT UNIQUE,
    acesso_senha TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS associados (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    associacao_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    telefone TEXT NOT NULL,
    endereco TEXT NOT NULL,
    numero TEXT,
    complemento TEXT,
    bairro TEXT,
    cep TEXT,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    nacionalidade TEXT,
    naturalidade TEXT,
    data_nascimento DATE,
    idade INTEGER,
    rg TEXT,
    rg_orgao_emissor TEXT,
    filiacao_1_nome TEXT,
    filiacao_1_cpf TEXT,
    filiacao_2_nome TEXT,
    filiacao_2_cpf TEXT,
    estado_civil TEXT,
    forma_comunhao TEXT,
    conjuge_nome TEXT,
    conjuge_cpf TEXT,
    profissao_1 TEXT,
    profissao_1_registro TEXT,
    profissao_1_orgao TEXT,
    profissao_2 TEXT,
    profissao_2_registro TEXT,
    profissao_2_orgao TEXT,
    doc_identidade TEXT,
    doc_identidade_status BOOLEAN DEFAULT 0,
    doc_identidade_validade DATE,
    doc_quitacao_eleitoral TEXT,
    doc_quitacao_eleitoral_status BOOLEAN DEFAULT 0,
    doc_quitacao_eleitoral_validade DATE,
    doc_fiscal_federal TEXT,
    doc_fiscal_federal_status BOOLEAN DEFAULT 0,
    doc_fiscal_federal_validade DATE,
    doc_fiscal_estadual TEXT,
    doc_fiscal_estadual_status BOOLEAN DEFAULT 0,
    doc_fiscal_estadual_validade DATE,
    doc_fiscal_municipal TEXT,
    doc_fiscal_municipal_status BOOLEAN DEFAULT 0,
    doc_fiscal_municipal_validade DATE,
    doc_situacao_cpf TEXT,
    doc_situacao_cpf_status BOOLEAN DEFAULT 0,
    doc_situacao_cpf_validade DATE,
    situacao BOOLEAN DEFAULT 0,
    validade DATE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (associacao_id) REFERENCES associacoes(id)
);
